#!/usr/bin/env ruby

require "yaml"
require "net/http"
require "json"
require "erb"

# Merge variables from .env file into environment.
env = YAML.load(File.read(File.join(__dir__, "releasenotes.env"))) rescue {}
env.each { |key, value| ENV[key] ||= value.to_s }

# Check if a single login is provided for both Bamboo and JIRA.
if ENV["bamboo_Atlassian_User"] && ENV["bamboo_Atlassian_Password"]
  ENV["bamboo_Bamboo_User"] = ENV["bamboo_JIRA_User"] = ENV["bamboo_Atlassian_User"]
  ENV["bamboo_Bamboo_Password"] = ENV["bamboo_JIRA_Password"] = ENV["bamboo_Atlassian_Password"]
end

# Check if all required variables are provided.
abort = false
%w[
  bamboo_JIRA_Server bamboo_Bamboo_Server bamboo_JIRA_User bamboo_JIRA_Password bamboo_Bamboo_User
  bamboo_Bamboo_Password bamboo_Plan_Key bamboo_Build_Number bamboo_Sprint_Field
].each do |var|
  unless ENV[var]
    puts "#{var.match(/bamboo_(.+)/)[1].gsub("_", " ")} not set!"
    abort = true
  end
end
exit! if abort

# Determine display mode.
DISPLAY_MODE = ENV["bamboo_Release_Notes_Mode"].downcase rescue "sprint"

# Base for both Bamboo and JIRA API.
API = Struct.new(:server, :user, :password) do
  def get(query)
    uri = URI.join(server, "/rest/api/latest/", query)
    request = Net::HTTP::Get.new(uri)
    request.basic_auth(user, password)
    request["Accept"] = "application/json"
    http = Net::HTTP.new(uri.hostname, uri.port)
    response = http.request(request)
    JSON.parse(response.body)
  end
end

# Set up Bamboo and JIRA APIs.
bamboo = API.new(ENV["bamboo_Bamboo_Server"], ENV["bamboo_Bamboo_User"], ENV["bamboo_Bamboo_Password"])
jira = API.new(ENV["bamboo_JIRA_Server"], ENV["bamboo_JIRA_User"], ENV["bamboo_JIRA_Password"])

# Fetch data of both build plan and current build from Bamboo, because build plan doesn't contain current build yet.
build_plan = bamboo.get("result/#{ENV["bamboo_Plan_Key"]}?expand=results.result.jiraIssues&max-result=100")
current_build = bamboo.get("result/#{ENV["bamboo_Plan_Key"]}-#{ENV["bamboo_Build_Number"]}?expand=jiraIssues")
all_builds = [current_build] + build_plan["results"]["result"]

# Generates URL for a specific build.
def build_url(build_number)
  URI.join(ENV["bamboo_Bamboo_Server"], "browse/", "#{ENV["bamboo_Plan_Key"]}-#{build_number}")
end

# A JIRA issue.
class Issue

  attr_accessor :key, :url, :type, :summary, :description, :status, :sprint, :build_number
  attr_accessor :parent, :children, :is_child, :blocker_keys

  def initialize(data)
    @key = data["key"]
    @url = URI.join(ENV["bamboo_JIRA_Server"], "browse/", @key)
    @type = data["fields"]["issuetype"]["name"]
    @summary = data["fields"]["summary"]
    @description = data["fields"]["description"]
    @status = data["fields"]["status"]["name"]
    @build_number = ""
    @children = []
    @is_child = false
    @parent = data["fields"]["parent"]["key"] if data["fields"]["parent"]
    # Extract sprint name by parsing custom field.
    @sprint = begin
      sprint = data["fields"][ENV["bamboo_Sprint_Field"]]
      sprint_data = sprint.first.match(/^.+\[(.+)\]$/)[1]
      parsed_sprint_data = Hash[sprint_data.split(",").collect { |s| s.split("=") }]
      parsed_sprint_data["name"]
    rescue
      "Backlog"
    end
    # Select keys of issues with an inward blocking relationship to this one.
    @blocker_keys = data["fields"]["issuelinks"].select do |link|
      link["type"]["name"] == "Blocks" && link["inwardIssue"]
    end.collect do |link|
      link["inwardIssue"]["key"]
    end
  end

  # Recursively generates markdown for this issue and its child issues.
  def to_md(level=0)
    issue_md = ("\t" * level) + "* [#{@type}: #{@summary}](#{@url}) (#{@status})"
    issue_md << " ([Build ##{@build_number}](#{build_url(@build_number)}))" if DISPLAY_MODE == "sprint"
    children_md = @children.collect { |child| child.to_md(level+1) }
    ([issue_md] + children_md) * "\n"
  end

end

# If allowed issue types are specified, construct respective query string with quoted types.
jql_issue_types = if ENV["bamboo_Issue_Types"]
  allowed_types = ENV["bamboo_Issue_Types"].split(/,\s?/).map { |type| %Q("#{type}") }
  " AND type in (#{allowed_types.join(",")})"
end

# Fetch JIRA issues for each build. Store all issues in a hash based on their key.
jira_issues = {}
all_builds.each do |build|
  issue_keys = build["jiraIssues"]["issue"].collect { |issue| issue["key"] }
  next if issue_keys.empty?
  jql_query = "key in (#{issue_keys.join(",")})#{jql_issue_types}"
  search_result = jira.get("search?jql=#{URI.encode(jql_query)}" +
    "&fields=summary,issuetype,status,parent,issuelinks,#{ENV["bamboo_Sprint_Field"]}" +
    "&maxResults=100&validateQuery=false")
  search_result["issues"].each do |issue_data|
    issue = Issue.new(issue_data)
    issue.build_number = build["planResultKey"]["resultNumber"]
    jira_issues[issue.key] = issue
  end
end

# Create relationships according to parent field and blocker keys.
# Only create relationships with issues that exist here and only within the same sprint.
jira_issues.each do |key, issue|
  # If issue has a parent issue, add this issue to its parent's children.
  if issue.parent && (parent = jira_issues[issue.parent]) && (parent.sprint == issue.sprint)
    parent.children << issue
    issue.is_child = true
  end
  # If issue has blockers, add blockers to this issues children.
  issue.blocker_keys.each do |blocker_key|
    if (blocker = jira_issues[blocker_key]) && (blocker.sprint == issue.sprint)
      issue.children << blocker
      blocker.is_child = true
    end
  end
end

# Remove child issues from top-level, then group top-level issues according to display mode.
display_issues = jira_issues.values.reject(&:is_child)
sections = case DISPLAY_MODE
  when "sprint" then display_issues.group_by(&:sprint)
  when "build" then display_issues.group_by { |issue| "Build ##{issue.build_number}" }
end

# Gather remaining data to display.
project_name = current_build["projectName"]
current_build_number = (if ENV["bamboo_Branch_Name"] then "#{ENV["bamboo_Branch_Name"]}-" else "#" end) + ENV["bamboo_Build_Number"]
current_build_url = build_url(ENV["bamboo_Build_Number"])
release_notes = ENV["bamboo_Release_Notes"]

# ERB template for release notes.
template = <<ERB
# <%= project_name %> ([Build <%= current_build_number %>](<%= current_build_url %>))

<%= release_notes %>

<% sections.each_pair do |section, issues| %>

## <%= section %>

<% issues.each do |issue| %>
<%= issue.to_md %>

<% end %>
<% end %>
ERB

# Render release notes to file.
output = ERB.new(template, nil, "<>").result(binding)
File.write(ENV["bamboo_Release_Notes_File"] || "releasenotes.md", output)
